<?php

namespace Drupal\fh_sight\Form;

use Drupal\Core\Entity\ContentEntityForm;
use Drupal\Core\Form\FormStateInterface;

/**
 * Form controller for the fh sight entity edit forms.
 */
class FhSightForm extends ContentEntityForm{

  public function buildForm(array $form, FormStateInterface $form_state)
  {
    $form = parent::buildForm($form, $form_state);
    return $form;
  }

  public function submitForm(array &$form, FormStateInterface $form_state)
  {
    parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  /**
   * {@inheritdoc}
   */
  public function save(array $form, FormStateInterface $form_state) {

    $entity = $this->getEntity();
    $result = $entity->save();
    $link = $entity->toLink($this->t('View'))->toRenderable();

    $message_arguments = ['%label' => $this->entity->label()];
    $logger_arguments = $message_arguments + ['link' => render($link)];

    if ($result == SAVED_NEW) {
      $this->messenger()->addStatus($this->t('New fh sight %label has been created.', $message_arguments));
      $this->logger('fh_sight')->notice('Created new fh sight %label', $logger_arguments);
    }
    else {
      $this->messenger()->addStatus($this->t('The fh sight %label has been updated.', $message_arguments));
      $this->logger('fh_sight')->notice('Updated new fh sight %label.', $logger_arguments);
    }

    $form_state->setRedirect('entity.fh_sight.canonical', ['fh_sight' => $entity->id()]);
  }

}
