<?php

namespace Drupal\fh_tour\Form;

use Drupal\Core\Entity\ContentEntityForm;
use Drupal\Core\Form\FormStateInterface;

/**
 * Form controller for the fh tour entity edit forms.
 */
class FhTourForm extends ContentEntityForm{

  public function buildForm(array $form, FormStateInterface $form_state)
  {
    $form = parent::buildForm($form, $form_state);

    // check if we have a default sight for the tour -> otherwise continue with empty sight reference
    // we get the sight ID from the route :)
    $default_sight_id = \Drupal::routeMatch()->getParameter('entity_id');
    if ($default_sight_id != 0) {
      $default_sight = \Drupal::entityTypeManager()->getStorage('fh_sight')->load($default_sight_id);
      $form['sights']['widget']['target_id']['#default_value'] = $default_sight;
    }
    return $form;
  }

  public function submitForm(array &$form, FormStateInterface $form_state)
  {
    parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  /**
   * {@inheritdoc}
   */
  public function save(array $form, FormStateInterface $form_state) {

    $entity = $this->getEntity();
    $result = $entity->save();
    $link = $entity->toLink($this->t('View'))->toRenderable();

    $message_arguments = ['%label' => $this->entity->label()];
    $logger_arguments = $message_arguments + ['link' => render($link)];

    if ($result == SAVED_NEW) {
      $this->messenger()->addStatus($this->t('New fh tour %label has been created.', $message_arguments));
      $this->logger('fh_tour')->notice('Created new fh tour %label', $logger_arguments);
    }
    else {
      $this->messenger()->addStatus($this->t('The fh tour %label has been updated.', $message_arguments));
      $this->logger('fh_tour')->notice('Updated new fh tour %label.', $logger_arguments);
    }

    $form_state->setRedirect('entity.fh_tour.canonical', ['fh_tour' => $entity->id()]);
  }

}
